BrowserCategory["VQM", None, {Item["ArgColorPlot Package", 
   "ArgColorPlot_Index.nb", IndexTag -> "VQM`ArgColorPlot`", 
   CopyTag -> None], BrowserCategory["Functions in ArgColorPlot", None, 
   {Item["QArgColorPlot", "ArgColorPlot.nb", CopyTag -> "QArgColorPlot", 
     IndexTag -> "QArgColorPlot"], Item["QListArgColorPlot", 
     "ArgColorPlot.nb", CopyTag -> "QListArgColorPlot", 
     IndexTag -> "QListArgColorPlot"], Item["QCombinedPlot", 
     "ArgColorPlot.nb", CopyTag -> "QCombinedPlot", 
     IndexTag -> "QCombinedPlot"], Item["QListCombinedPlot", 
     "ArgColorPlot.nb", CopyTag -> "QListCombinedPlot", 
     IndexTag -> "QListCombinedPlot"], Item["QSpinorPlot", "ArgColorPlot.nb", 
     CopyTag -> "QSpinorPlot", IndexTag -> "QSpinorPlot"], 
    Item["QListSpinorPlot", "ArgColorPlot.nb", CopyTag -> "QListSpinorPlot", 
     IndexTag -> "QListSpinorPlot"], Item["QSpinorCombinedPlot", 
     "ArgColorPlot.nb", CopyTag -> "QSpinorCombinedPlot", 
     IndexTag -> "QSpinorCombinedPlot"], Item["QListSpinorCombinedPlot", 
     "ArgColorPlot.nb", CopyTag -> "QListSpinorCombinedPlot", 
     IndexTag -> "QListSpinorCombinedPlot"], Item["QNiceTicks", 
     "ArgColorPlot.nb", CopyTag -> "QNiceTicks", IndexTag -> "QNiceTicks"]}], 
  Item[Delimiter], Item["ColorMaps Package", "ColorMaps_Index.nb", 
   IndexTag -> "VQM`ColorMaps`", CopyTag -> None], 
  BrowserCategory["Functions in ColorMaps", None, 
   {Item["QComplexToColor", "ColorMaps.nb", CopyTag -> "QComplexToColor", 
     IndexTag -> "QComplexToColor"], Item["QRGBValues", "ColorMaps.nb", 
     CopyTag -> "QRGBValues", IndexTag -> "QRGBValues"], 
    Item["QComplexToRGBColor", "ColorMaps.nb", 
     CopyTag -> "QComplexToRGBColor", IndexTag -> "QComplexToRGBColor"], 
    Item["$QComplexToColorMap", "ColorMaps.nb", 
     CopyTag -> "$QComplexToColorMap", IndexTag -> "$QComplexToColorMap"], 
    Item["QSaturationFromLightness", "ColorMaps.nb", 
     CopyTag -> "QSaturationFromLightness", 
     IndexTag -> "QSaturationFromLightness"], 
    Item["QBrightnessFromLightness", "ColorMaps.nb", 
     CopyTag -> "QBrightnessFromLightness", 
     IndexTag -> "QBrightnessFromLightness"], Item["QHueFromArgument", 
     "ColorMaps.nb", CopyTag -> "QHueFromArgument", 
     IndexTag -> "QHueFromArgument"], Item["QLightnessFromModulus", 
     "ColorMaps.nb", CopyTag -> "QLightnessFromModulus", 
     IndexTag -> "QLightnessFromModulus"], Item["QProcessColorMapOptions", 
     "ColorMaps.nb", CopyTag -> "QProcessColorMapOptions", 
     IndexTag -> "QProcessColorMapOptions"], Item["QVectorToColor", 
     "ColorMaps.nb", CopyTag -> "QVectorToColor", 
     IndexTag -> "QVectorToColor"], Item["QSpinorToColor", "ColorMaps.nb", 
     CopyTag -> "QSpinorToColor", IndexTag -> "QSpinorToColor"]}], 
  Item[Delimiter], Item["ComplexPlot Package", "ComplexPlot_Index.nb", 
   IndexTag -> "VQM`ComplexPlot`", CopyTag -> None], 
  BrowserCategory["Functions in ComplexPlot", None, 
   {Item["QComplexPlot3D", "ComplexPlot.nb", CopyTag -> "QComplexPlot3D", 
     IndexTag -> "QComplexPlot3D"], Item["QListComplexPlot3D", 
     "ComplexPlot.nb", CopyTag -> "QListComplexPlot3D", 
     IndexTag -> "QListComplexPlot3D"], Item["QComplexSurfacePlot", 
     "ComplexPlot.nb", CopyTag -> "QComplexSurfacePlot", 
     IndexTag -> "QComplexSurfacePlot"], Item["QListComplexSurfacePlot", 
     "ComplexPlot.nb", CopyTag -> "QListComplexSurfacePlot", 
     IndexTag -> "QListComplexSurfacePlot"], Item["QComplexDensityPlot", 
     "ComplexPlot.nb", CopyTag -> "QComplexDensityPlot", 
     IndexTag -> "QComplexDensityPlot"], Item["QSpinorDensityPlot", 
     "ComplexPlot.nb", CopyTag -> "QSpinorDensityPlot", 
     IndexTag -> "QSpinorDensityPlot"], Item["QListComplexDensityPlot", 
     "ComplexPlot.nb", CopyTag -> "QListComplexDensityPlot", 
     IndexTag -> "QListComplexDensityPlot"], Item["QComplexContourPlot", 
     "ComplexPlot.nb", CopyTag -> "QComplexContourPlot", 
     IndexTag -> "QComplexContourPlot"], Item["QListComplexContourPlot", 
     "ComplexPlot.nb", CopyTag -> "QListComplexContourPlot", 
     IndexTag -> "QListComplexContourPlot"], Item["QColorArrayPlot", 
     "ComplexPlot.nb", CopyTag -> "QColorArrayPlot", 
     IndexTag -> "QColorArrayPlot"], Item["QColorDensityGraphics", 
     "ComplexPlot.nb", CopyTag -> "QColorDensityGraphics", 
     IndexTag -> "QColorDensityGraphics"]}], Item[Delimiter], 
  Item["Coulomb Package", "Coulomb_Index.nb", IndexTag -> "VQM`Coulomb`", 
   CopyTag -> None], BrowserCategory["Functions in Coulomb", None, 
   {Item["QPrincipalQuantumNumber", "Coulomb.nb", 
     CopyTag -> "QPrincipalQuantumNumber", IndexTag -> 
      "QPrincipalQuantumNumber"], Item["QRadialQuantumNumber", "Coulomb.nb", 
     CopyTag -> "QRadialQuantumNumber", IndexTag -> "QRadialQuantumNumber"], 
    Item["QCoulombEnergy", "Coulomb.nb", CopyTag -> "QCoulombEnergy", 
     IndexTag -> "QCoulombEnergy"], Item["QCoulombTimePeriod", "Coulomb.nb", 
     CopyTag -> "QCoulombTimePeriod", IndexTag -> "QCoulombTimePeriod"], 
    Item["QCoulombFunction", "Coulomb.nb", CopyTag -> "QCoulombFunction", 
     IndexTag -> "QCoulombFunction"], Item["QEffectiveCoulombPotential", 
     "Coulomb.nb", CopyTag -> "QEffectiveCoulombPotential", 
     IndexTag -> "QEffectiveCoulombPotential"], Item["QCoulombHamiltonian", 
     "Coulomb.nb", CopyTag -> "QCoulombHamiltonian", 
     IndexTag -> "QCoulombHamiltonian"], Item["QRadialCoulombFunction", 
     "Coulomb.nb", CopyTag -> "QRadialCoulombFunction", 
     IndexTag -> "QRadialCoulombFunction"], Item["QRadialPositionAmplitude", 
     "Coulomb.nb", CopyTag -> "QRadialPositionAmplitude", 
     IndexTag -> "QRadialPositionAmplitude"], Item["$QCoulombSpaceDimension", 
     "Coulomb.nb", CopyTag -> "$QCoulombSpaceDimension", 
     IndexTag -> "$QCoulombSpaceDimension"], Item["$QCoulombCoupling", 
     "Coulomb.nb", CopyTag -> "$QCoulombCoupling", 
     IndexTag -> "$QCoulombCoupling"]}], Item[Delimiter], 
  Item["Dirac1D Package", "Dirac1D_Index.nb", IndexTag -> "VQM`Dirac1D`", 
   CopyTag -> None], BrowserCategory["Functions in Dirac1D", None, 
   {Item["QRelativisticEnergy", "Dirac1D.nb", 
     CopyTag -> "QRelativisticEnergy", IndexTag -> "QRelativisticEnergy"], 
    Item["QRelativisticVelocity", "Dirac1D.nb", 
     CopyTag -> "QRelativisticVelocity", IndexTag -> 
      "QRelativisticVelocity"], Item["QSignedEnergy", "Dirac1D.nb", 
     CopyTag -> "QSignedEnergy", IndexTag -> "QSignedEnergy"], 
    Item["QSignedMomentum", "Dirac1D.nb", CopyTag -> "QSignedMomentum", 
     IndexTag -> "QSignedMomentum"], Item["aplus", "Dirac1D.nb", 
     CopyTag -> "aplus", IndexTag -> "aplus"], Item["aminus", "Dirac1D.nb", 
     CopyTag -> "aminus", IndexTag -> "aminus"], Item["QDiracMatrix1D", 
     "Dirac1D.nb", CopyTag -> "QDiracMatrix1D", 
     IndexTag -> "QDiracMatrix1D"], Item["QProjectPositiveEnergy", 
     "Dirac1D.nb", CopyTag -> "QProjectPositiveEnergy", 
     IndexTag -> "QProjectPositiveEnergy"], Item["QProjectNegativeEnergy", 
     "Dirac1D.nb", CopyTag -> "QProjectNegativeEnergy", 
     IndexTag -> "QProjectNegativeEnergy"], Item["QMomentumSpacePropagator", 
     "Dirac1D.nb", CopyTag -> "QMomentumSpacePropagator", 
     IndexTag -> "QMomentumSpacePropagator"], Item["QBaseSpinorRight", 
     "Dirac1D.nb", CopyTag -> "QBaseSpinorRight", 
     IndexTag -> "QBaseSpinorRight"], Item["QBaseSpinorLeft", "Dirac1D.nb", 
     CopyTag -> "QBaseSpinorLeft", IndexTag -> "QBaseSpinorLeft"], 
    Item["QBaseSpinorPos", "Dirac1D.nb", CopyTag -> "QBaseSpinorPos", 
     IndexTag -> "QBaseSpinorPos"], Item["QBaseSpinorNeg", "Dirac1D.nb", 
     CopyTag -> "QBaseSpinorNeg", IndexTag -> "QBaseSpinorNeg"], 
    Item["QDiracPlaneWaveRight", "Dirac1D.nb", 
     CopyTag -> "QDiracPlaneWaveRight", IndexTag -> "QDiracPlaneWaveRight"], 
    Item["QDiracPlaneWaveLeft", "Dirac1D.nb", 
     CopyTag -> "QDiracPlaneWaveLeft", IndexTag -> "QDiracPlaneWaveLeft"], 
    Item["QDiracPlaneWavePos", "Dirac1D.nb", CopyTag -> "QDiracPlaneWavePos", 
     IndexTag -> "QDiracPlaneWavePos"], Item["QDiracPlaneWaveNeg", 
     "Dirac1D.nb", CopyTag -> "QDiracPlaneWaveNeg", 
     IndexTag -> "QDiracPlaneWaveNeg"], Item["QFWMatrix", "Dirac1D.nb", 
     CopyTag -> "QFWMatrix", IndexTag -> "QFWMatrix"], 
    Item["$c", "Dirac1D.nb", CopyTag -> "$c", IndexTag -> "$c"], 
    Item["$m", "Dirac1D.nb", CopyTag -> "$m", IndexTag -> "$m"], 
    Item["QDiracEquation1D", "Dirac1D.nb", CopyTag -> "QDiracEquation1D", 
     IndexTag -> "QDiracEquation1D"], Item["QDiracOperator1D", "Dirac1D.nb", 
     CopyTag -> "QDiracOperator1D", IndexTag -> "QDiracOperator1D"], 
    Item["QTridiagonalBlockSolve", "Dirac1D.nb", 
     CopyTag -> "QTridiagonalBlockSolve", IndexTag -> 
      "QTridiagonalBlockSolve"], Item["QDiracTimeStep1D", "Dirac1D.nb", 
     CopyTag -> "QDiracTimeStep1D", IndexTag -> "QDiracTimeStep1D"], 
    Item["QInitializeDirac1D", "Dirac1D.nb", CopyTag -> "QInitializeDirac1D", 
     IndexTag -> "QInitializeDirac1D"], Item["QMomentumSpaceSpinorPos", 
     "Dirac1D.nb", CopyTag -> "QMomentumSpaceSpinorPos", 
     IndexTag -> "QMomentumSpaceSpinorPos"], Item["QMomentumSpaceSpinorNeg", 
     "Dirac1D.nb", CopyTag -> "QMomentumSpaceSpinorNeg", 
     IndexTag -> "QMomentumSpaceSpinorNeg"], 
    Item["QMomentumSpaceSpinorRight", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorRight", 
     IndexTag -> "QMomentumSpaceSpinorRight"], 
    Item["QMomentumSpaceSpinorLeft", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorLeft", 
     IndexTag -> "QMomentumSpaceSpinorLeft"], 
    Item["QMomentumSpaceSpinorPosRight", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorPosRight", 
     IndexTag -> "QMomentumSpaceSpinorPosRight"], 
    Item["QMomentumSpaceSpinorPosLeft", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorPosLeft", 
     IndexTag -> "QMomentumSpaceSpinorPosLeft"], 
    Item["QMomentumSpaceSpinorNegRight", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorNegRight", 
     IndexTag -> "QMomentumSpaceSpinorNegRight"], 
    Item["QMomentumSpaceSpinorNegLeft", "Dirac1D.nb", 
     CopyTag -> "QMomentumSpaceSpinorNegLeft", 
     IndexTag -> "QMomentumSpaceSpinorNegLeft"], Item["QMomentumSpaceSpinor", 
     "Dirac1D.nb", CopyTag -> "QMomentumSpaceSpinor", 
     IndexTag -> "QMomentumSpaceSpinor"], Item["QPositionSpaceSpinor", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceSpinor", 
     IndexTag -> "QPositionSpaceSpinor"], Item["QPositionSpaceSpinorPos", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceSpinorPos", 
     IndexTag -> "QPositionSpaceSpinorPos"], Item["QPositionSpaceSpinorNeg", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceSpinorNeg", 
     IndexTag -> "QPositionSpaceSpinorNeg"], 
    Item["QPositionSpaceSpinorRight", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorRight", 
     IndexTag -> "QPositionSpaceSpinorRight"], 
    Item["QPositionSpaceSpinorLeft", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorLeft", 
     IndexTag -> "QPositionSpaceSpinorLeft"], 
    Item["QPositionSpaceSpinorPosRight", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorPosRight", 
     IndexTag -> "QPositionSpaceSpinorPosRight"], 
    Item["QPositionSpaceSpinorPosLeft", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorPosLeft", 
     IndexTag -> "QPositionSpaceSpinorPosLeft"], 
    Item["QPositionSpaceSpinorNegRight", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorNegRight", 
     IndexTag -> "QPositionSpaceSpinorNegRight"], 
    Item["QPositionSpaceSpinorNegLeft", "Dirac1D.nb", 
     CopyTag -> "QPositionSpaceSpinorNegLeft", 
     IndexTag -> "QPositionSpaceSpinorNegLeft"], Item["QPositionSpaceGrid", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceGrid", 
     IndexTag -> "QPositionSpaceGrid"], Item["QPositionSpaceInterval", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceInterval", 
     IndexTag -> "QPositionSpaceInterval"], Item["QPositionSpaceStep", 
     "Dirac1D.nb", CopyTag -> "QPositionSpaceStep", 
     IndexTag -> "QPositionSpaceStep"], Item["QComputeMeanPosition", 
     "Dirac1D.nb", CopyTag -> "QComputeMeanPosition", 
     IndexTag -> "QComputeMeanPosition"], Item["QInnerProductList", 
     "Dirac1D.nb", CopyTag -> "QInnerProductList", 
     IndexTag -> "QInnerProductList"], Item["QSpinorFT", "Dirac1D.nb", 
     CopyTag -> "QSpinorFT", IndexTag -> "QSpinorFT"], 
    Item["QInverseSpinorFT", "Dirac1D.nb", CopyTag -> "QInverseSpinorFT", 
     IndexTag -> "QInverseSpinorFT"]}], Item[Delimiter], 
  Item["FastFourier Package", "FastFourier_Index.nb", 
   IndexTag -> "VQM`FastFourier`", CopyTag -> None], 
  BrowserCategory["Functions in FastFourier", None, 
   {Item["QFourierList", "FastFourier.nb", CopyTag -> "QFourierList", 
     IndexTag -> "QFourierList"], Item["QInverseFourierList", 
     "FastFourier.nb", CopyTag -> "QInverseFourierList", 
     IndexTag -> "QInverseFourierList"], Item["QFourierListArgColorPlot", 
     "FastFourier.nb", CopyTag -> "QFourierListArgColorPlot", 
     IndexTag -> "QFourierListArgColorPlot"], 
    Item["QInverseFourierListArgColorPlot", "FastFourier.nb", 
     CopyTag -> "QInverseFourierListArgColorPlot", 
     IndexTag -> "QInverseFourierListArgColorPlot"], 
    Item["QStepSize", "FastFourier.nb", CopyTag -> "QStepSize", 
     IndexTag -> "QStepSize"], Item["QGrid", "FastFourier.nb", 
     CopyTag -> "QGrid", IndexTag -> "QGrid"], Item["QLeftBorder", 
     "FastFourier.nb", CopyTag -> "QLeftBorder", IndexTag -> "QLeftBorder"], 
    Item["QSpaceStep", "FastFourier.nb", CopyTag -> "QSpaceStep", 
     IndexTag -> "QSpaceStep"], Item["QSpaceInterval", "FastFourier.nb", 
     CopyTag -> "QSpaceInterval", IndexTag -> "QSpaceInterval"], 
    Item["QIndexPosition", "FastFourier.nb", CopyTag -> "QIndexPosition", 
     IndexTag -> "QIndexPosition"], Item["QFourierGrid", "FastFourier.nb", 
     CopyTag -> "QFourierGrid", IndexTag -> "QFourierGrid"], 
    Item["QFourierLeftBorder", "FastFourier.nb", 
     CopyTag -> "QFourierLeftBorder", IndexTag -> "QFourierLeftBorder"], 
    Item["QFourierRightBorder", "FastFourier.nb", 
     CopyTag -> "QFourierRightBorder", IndexTag -> "QFourierRightBorder"], 
    Item["QFourierStep", "FastFourier.nb", CopyTag -> "QFourierStep", 
     IndexTag -> "QFourierStep"], Item["QFourierInterval", "FastFourier.nb", 
     CopyTag -> "QFourierInterval", IndexTag -> "QFourierInterval"]}], 
  Item[Delimiter], Item["Free Package", "Free_Index.nb", 
   IndexTag -> "VQM`Free`", CopyTag -> None], 
  BrowserCategory["Functions in Free", None, 
   {Item["QFreeHamiltonian1D", "Free.nb", CopyTag -> "QFreeHamiltonian1D", 
     IndexTag -> "QFreeHamiltonian1D"], Item["QFreeGaussian", "Free.nb", 
     CopyTag -> "QFreeGaussian", IndexTag -> "QFreeGaussian"], 
    Item["QFreeGaussian1D", "Free.nb", CopyTag -> "QFreeGaussian1D", 
     IndexTag -> "QFreeGaussian1D"], Item["QFreeGaussian2D", "Free.nb", 
     CopyTag -> "QFreeGaussian2D", IndexTag -> "QFreeGaussian2D"], 
    Item["QFreeGaussian3D", "Free.nb", CopyTag -> "QFreeGaussian3D", 
     IndexTag -> "QFreeGaussian3D"], Item["QGaussian1D", "Free.nb", 
     CopyTag -> "QGaussian1D", IndexTag -> "QGaussian1D"], 
    Item["QGaussian2D", "Free.nb", CopyTag -> "QGaussian2D", 
     IndexTag -> "QGaussian2D"], Item["QGaussian3D", "Free.nb", 
     CopyTag -> "QGaussian3D", IndexTag -> "QGaussian3D"], 
    Item["QFreeFourierGaussian1D", "Free.nb", 
     CopyTag -> "QFreeFourierGaussian1D", IndexTag -> 
      "QFreeFourierGaussian1D"], Item["QFourierGaussian1D", "Free.nb", 
     CopyTag -> "QFourierGaussian1D", IndexTag -> "QFourierGaussian1D"], 
    Item["QEnergyGaussian1D", "Free.nb", CopyTag -> "QEnergyGaussian1D", 
     IndexTag -> "QEnergyGaussian1D"], Item["$QFreeMass", "Free.nb", 
     CopyTag -> "$QFreeMass", IndexTag -> "$QFreeMass"], 
    Item["$QFreeSpaceDimension", "Free.nb", 
     CopyTag -> "$QFreeSpaceDimension", IndexTag -> 
      "$QFreeSpaceDimension"]}], Item[Delimiter], 
  Item["Oscillator Package", "Oscillator_Index.nb", 
   IndexTag -> "VQM`Oscillator`", CopyTag -> None], 
  BrowserCategory["Functions in Oscillator", None, 
   {Item["QOscillatorEnergy", "Oscillator.nb", 
     CopyTag -> "QOscillatorEnergy", IndexTag -> "QOscillatorEnergy"], 
    Item["QOscillatorFunction", "Oscillator.nb", 
     CopyTag -> "QOscillatorFunction", IndexTag -> "QOscillatorFunction"], 
    Item["QOscillatorGaussian", "Oscillator.nb", 
     CopyTag -> "QOscillatorGaussian", IndexTag -> "QOscillatorGaussian"], 
    Item["QOscillatorBarDiagram", "Oscillator.nb", 
     CopyTag -> "QOscillatorBarDiagram", IndexTag -> 
      "QOscillatorBarDiagram"], Item["$QOscillatorFrequency", 
     "Oscillator.nb", CopyTag -> "$QOscillatorFrequency", 
     IndexTag -> "$QOscillatorFrequency"], Item["$QOscillatorMass", 
     "Oscillator.nb", CopyTag -> "$QOscillatorMass", 
     IndexTag -> "$QOscillatorMass"]}], Item[Delimiter], 
  Item["QGraphics2D Package", "QGraphics2D_Index.nb", 
   IndexTag -> "VQM`QGraphics2D`", CopyTag -> None], 
  BrowserCategory["Functions in QGraphics2D", None, 
   {Item["QPrepareOptions", "QGraphics2D.nb", CopyTag -> "QPrepareOptions", 
     IndexTag -> "QPrepareOptions"], Item["QExtractPart", "QGraphics2D.nb", 
     CopyTag -> "QExtractPart", IndexTag -> "QExtractPart"], 
    Item["QGetAndDensityPlot", "QGraphics2D.nb", 
     CopyTag -> "QGetAndDensityPlot", IndexTag -> "QGetAndDensityPlot"], 
    Item["QGetAndComplexDensityPlot", "QGraphics2D.nb", 
     CopyTag -> "QGetAndComplexDensityPlot", 
     IndexTag -> "QGetAndComplexDensityPlot"], 
    Item["QGetSpinorAndDensityPlot", "QGraphics2D.nb", 
     CopyTag -> "QGetSpinorAndDensityPlot", 
     IndexTag -> "QGetSpinorAndDensityPlot"], Item["QMakeTable", 
     "QGraphics2D.nb", CopyTag -> "QMakeTable", IndexTag -> "QMakeTable"], 
    Item["QZeroTable", "QGraphics2D.nb", CopyTag -> "QZeroTable", 
     IndexTag -> "QZeroTable"], Item["QGetSpinorAndDensityPlotTwo", 
     "QGraphics2D.nb", CopyTag -> "QGetSpinorAndDensityPlotTwo", 
     IndexTag -> "QGetSpinorAndDensityPlotTwo"], 
    Item["QGetAndSpinorToColorPlot", "QGraphics2D.nb", 
     CopyTag -> "QGetAndSpinorToColorPlot", 
     IndexTag -> "QGetAndSpinorToColorPlot"], 
    Item["QGetAndSpinorToColorPlotTwo", "QGraphics2D.nb", 
     CopyTag -> "QGetAndSpinorToColorPlotTwo", 
     IndexTag -> "QGetAndSpinorToColorPlotTwo"]}], Item[Delimiter], 
  Item["QuantumKernel Package", "QuantumKernel_Index.nb", 
   IndexTag -> "VQM`QuantumKernel`", CopyTag -> None], 
  BrowserCategory["Functions in QuantumKernel", None, 
   {Item["QNewFunction", "QuantumKernel.nb", CopyTag -> "QNewFunction", 
     IndexTag -> "QNewFunction"], Item["QDisposeFunction", 
     "QuantumKernel.nb", CopyTag -> "QDisposeFunction", 
     IndexTag -> "QDisposeFunction"], Item["QGetArray", "QuantumKernel.nb", 
     CopyTag -> "QGetArray", IndexTag -> "QGetArray"], 
    Item["QGetFunctionInfo", "QuantumKernel.nb", 
     CopyTag -> "QGetFunctionInfo", IndexTag -> "QGetFunctionInfo"], 
    Item["QGetColorArray", "QuantumKernel.nb", CopyTag -> "QGetColorArray", 
     IndexTag -> "QGetColorArray"], Item["QGetGrayArray", "QuantumKernel.nb", 
     CopyTag -> "QGetGrayArray", IndexTag -> "QGetGrayArray"], 
    Item["QGetRedBlueArray", "QuantumKernel.nb", 
     CopyTag -> "QGetRedBlueArray", IndexTag -> "QGetRedBlueArray"], 
    Item["QGetBlackWhiteArray", "QuantumKernel.nb", 
     CopyTag -> "QGetBlackWhiteArray", IndexTag -> "QGetBlackWhiteArray"], 
    Item["QGetAbsArray", "QuantumKernel.nb", CopyTag -> "QGetAbsArray", 
     IndexTag -> "QGetAbsArray"], Item["QInfo", "QuantumKernel.nb", 
     CopyTag -> "QInfo", IndexTag -> "QInfo"], Item["QSchroedinger1D", 
     "QuantumKernel.nb", CopyTag -> "QSchroedinger1D", 
     IndexTag -> "QSchroedinger1D"], Item["QSchroedinger2D", 
     "QuantumKernel.nb", CopyTag -> "QSchroedinger2D", 
     IndexTag -> "QSchroedinger2D"], Item["QSchroedinger3D", 
     "QuantumKernel.nb", CopyTag -> "QSchroedinger3D", 
     IndexTag -> "QSchroedinger3D"], Item["QPauli2D", "QuantumKernel.nb", 
     CopyTag -> "QPauli2D", IndexTag -> "QPauli2D"], 
    Item["QPauli3D", "QuantumKernel.nb", CopyTag -> "QPauli3D", 
     IndexTag -> "QPauli3D"], Item["QDirac2D", "QuantumKernel.nb", 
     CopyTag -> "QDirac2D", IndexTag -> "QDirac2D"], 
    Item["QDirac3D", "QuantumKernel.nb", CopyTag -> "QDirac3D", 
     IndexTag -> "QDirac3D"], Item["QDisposeOperator", "QuantumKernel.nb", 
     CopyTag -> "QDisposeOperator", IndexTag -> "QDisposeOperator"], 
    Item["QGetOperatorInfo", "QuantumKernel.nb", 
     CopyTag -> "QGetOperatorInfo", IndexTag -> "QGetOperatorInfo"], 
    Item["QTimeEvolution", "QuantumKernel.nb", CopyTag -> "QTimeEvolution", 
     IndexTag -> "QTimeEvolution"]}], Item[Delimiter], 
  Item["Rectangular Package", "Rectangular_Index.nb", 
   IndexTag -> "VQM`Rectangular`", CopyTag -> None], 
  BrowserCategory["Functions in Rectangular", None, 
   {Item["QPlaneWaveToRight", "Rectangular.nb", 
     CopyTag -> "QPlaneWaveToRight", IndexTag -> "QPlaneWaveToRight"], 
    Item["QPlaneWaveToLeft", "Rectangular.nb", CopyTag -> "QPlaneWaveToLeft", 
     IndexTag -> "QPlaneWaveToLeft"], Item["QReflectionCoefficientJump", 
     "Rectangular.nb", CopyTag -> "QReflectionCoefficientJump", 
     IndexTag -> "QReflectionCoefficientJump"], 
    Item["QTransmissionCoefficientJump", "Rectangular.nb", 
     CopyTag -> "QTransmissionCoefficientJump", 
     IndexTag -> "QTransmissionCoefficientJump"], 
    Item["QReflectionCoefficientWell", "Rectangular.nb", 
     CopyTag -> "QReflectionCoefficientWell", 
     IndexTag -> "QReflectionCoefficientWell"], 
    Item["QTransmissionCoefficientWell", "Rectangular.nb", 
     CopyTag -> "QTransmissionCoefficientWell", 
     IndexTag -> "QTransmissionCoefficientWell"], Item["QTransitionMatrix", 
     "Rectangular.nb", CopyTag -> "QTransitionMatrix", 
     IndexTag -> "QTransitionMatrix"], Item["QSolutionWellToRight", 
     "Rectangular.nb", CopyTag -> "QSolutionWellToRight", 
     IndexTag -> "QSolutionWellToRight"], Item["QPsiEvenWell", 
     "Rectangular.nb", CopyTag -> "QPsiEvenWell", 
     IndexTag -> "QPsiEvenWell"], Item["QPsiOddWell", "Rectangular.nb", 
     CopyTag -> "QPsiOddWell", IndexTag -> "QPsiOddWell"], 
    Item["QDetEvenWell", "Rectangular.nb", CopyTag -> "QDetEvenWell", 
     IndexTag -> "QDetEvenWell"], Item["QDetOddWell", "Rectangular.nb", 
     CopyTag -> "QDetOddWell", IndexTag -> "QDetOddWell"], 
    Item["QCriticalRadiusEvenWell", "Rectangular.nb", 
     CopyTag -> "QCriticalRadiusEvenWell", IndexTag -> 
      "QCriticalRadiusEvenWell"], Item["QCriticalRadiusOddWell", 
     "Rectangular.nb", CopyTag -> "QCriticalRadiusOddWell", 
     IndexTag -> "QCriticalRadiusOddWell"], Item["QCriticalDepthEvenWell", 
     "Rectangular.nb", CopyTag -> "QCriticalDepthEvenWell", 
     IndexTag -> "QCriticalDepthEvenWell"], Item["QCriticalDepthOddWell", 
     "Rectangular.nb", CopyTag -> "QCriticalDepthOddWell", 
     IndexTag -> "QCriticalDepthOddWell"]}], Item[Delimiter], 
  Item["Spinors Package", "Spinors_Index.nb", IndexTag -> "VQM`Spinors`", 
   CopyTag -> None], BrowserCategory["Functions in Spinors", None, 
   {Item["QNorm", "Spinors.nb", CopyTag -> "QNorm", IndexTag -> "QNorm"], 
    Item["QNormalize", "Spinors.nb", CopyTag -> "QNormalize", 
     IndexTag -> "QNormalize"], Item["$QSpinBasis", "Spinors.nb", 
     CopyTag -> "$QSpinBasis", IndexTag -> "$QSpinBasis"], 
    Item["QSetSpinBasis", "Spinors.nb", CopyTag -> "QSetSpinBasis", 
     IndexTag -> "QSetSpinBasis"], Item["QSpinorToComponents", "Spinors.nb", 
     CopyTag -> "QSpinorToComponents", IndexTag -> "QSpinorToComponents"], 
    Item["QComponentsToSpinor", "Spinors.nb", 
     CopyTag -> "QComponentsToSpinor", IndexTag -> "QComponentsToSpinor"], 
    Item["QProjectUp", "Spinors.nb", CopyTag -> "QProjectUp", 
     IndexTag -> "QProjectUp"], Item["QProjectDown", "Spinors.nb", 
     CopyTag -> "QProjectDown", IndexTag -> "QProjectDown"], 
    Item["QProbabilityUp", "Spinors.nb", CopyTag -> "QProbabilityUp", 
     IndexTag -> "QProbabilityUp"], Item["QSpinorBarDiagram", "Spinors.nb", 
     CopyTag -> "QSpinorBarDiagram", IndexTag -> "QSpinorBarDiagram"], 
    Item["QVectorToHermitianMatrix", "Spinors.nb", 
     CopyTag -> "QVectorToHermitianMatrix", 
     IndexTag -> "QVectorToHermitianMatrix"], Item["QVectorToDensityMatrix", 
     "Spinors.nb", CopyTag -> "QVectorToDensityMatrix", 
     IndexTag -> "QVectorToDensityMatrix"], Item["QSpinHamiltonian", 
     "Spinors.nb", CopyTag -> "QSpinHamiltonian", 
     IndexTag -> "QSpinHamiltonian"], Item["QSpinorUp", "Spinors.nb", 
     CopyTag -> "QSpinorUp", IndexTag -> "QSpinorUp"], 
    Item["QSpinorDown", "Spinors.nb", CopyTag -> "QSpinorDown", 
     IndexTag -> "QSpinorDown"], Item["QConjSpinorUp", "Spinors.nb", 
     CopyTag -> "QConjSpinorUp", IndexTag -> "QConjSpinorUp"], 
    Item["QConjSpinorDown", "Spinors.nb", CopyTag -> "QConjSpinorDown", 
     IndexTag -> "QConjSpinorDown"], Item["QSpinorHarmonicUp", "Spinors.nb", 
     CopyTag -> "QSpinorHarmonicUp", IndexTag -> "QSpinorHarmonicUp"], 
    Item["QSpinorHarmonicDown", "Spinors.nb", 
     CopyTag -> "QSpinorHarmonicDown", IndexTag -> "QSpinorHarmonicDown"], 
    Item["QSpinorToVector", "Spinors.nb", CopyTag -> "QSpinorToVector", 
     IndexTag -> "QSpinorToVector"], Item["QVectorToSpinor", "Spinors.nb", 
     CopyTag -> "QVectorToSpinor", IndexTag -> "QVectorToSpinor"], 
    Item["QExtractPhase", "Spinors.nb", CopyTag -> "QExtractPhase", 
     IndexTag -> "QExtractPhase"], Item["QHermitianMatrixToVector", 
     "Spinors.nb", CopyTag -> "QHermitianMatrixToVector", 
     IndexTag -> "QHermitianMatrixToVector"], Item["QDensityMatrixToVector", 
     "Spinors.nb", CopyTag -> "QDensityMatrixToVector", 
     IndexTag -> "QDensityMatrixToVector"], Item["QSpinorToArrow", 
     "Spinors.nb", CopyTag -> "QSpinorToArrow", 
     IndexTag -> "QSpinorToArrow"], Item["QRotationSO3", "Spinors.nb", 
     CopyTag -> "QRotationSO3", IndexTag -> "QRotationSO3"], 
    Item["QRotationSU2", "Spinors.nb", CopyTag -> "QRotationSU2", 
     IndexTag -> "QRotationSU2"], Item["QVisualizeSpinor", "Spinors.nb", 
     CopyTag -> "QVisualizeSpinor", IndexTag -> "QVisualizeSpinor"], 
    Item["QVisualizeDensityMatrix", "Spinors.nb", 
     CopyTag -> "QVisualizeDensityMatrix", IndexTag -> 
      "QVisualizeDensityMatrix"]}], Item[Delimiter], 
  Item["VisualizeVector Package", "VisualizeVector_Index.nb", 
   IndexTag -> "VQM`VisualizeVector`", CopyTag -> None], 
  BrowserCategory["Functions in VisualizeVector", None, 
   {Item["QVectorToArrow", "VisualizeVector.nb", CopyTag -> "QVectorToArrow", 
     IndexTag -> "QVectorToArrow"], Item["QVisualizeVector", 
     "VisualizeVector.nb", CopyTag -> "QVisualizeVector", 
     IndexTag -> "QVisualizeVector"], Item["polyDisk", "VisualizeVector.nb", 
     CopyTag -> "polyDisk", IndexTag -> "polyDisk"], 
    Item["polyCone", "VisualizeVector.nb", CopyTag -> "polyCone", 
     IndexTag -> "polyCone"], Item["polyCylinder", "VisualizeVector.nb", 
     CopyTag -> "polyCylinder", IndexTag -> "polyCylinder"], 
    Item["arrowCone", "VisualizeVector.nb", CopyTag -> "arrowCone", 
     IndexTag -> "arrowCone"], Item["arrowWithShaft", "VisualizeVector.nb", 
     CopyTag -> "arrowWithShaft", IndexTag -> "arrowWithShaft"], 
    Item["doubleHead", "VisualizeVector.nb", CopyTag -> "doubleHead", 
     IndexTag -> "doubleHead"], Item["unitSphere", "VisualizeVector.nb", 
     CopyTag -> "unitSphere", IndexTag -> "unitSphere"], 
    Item["QRoundSphere", "VisualizeVector.nb", CopyTag -> "QRoundSphere", 
     IndexTag -> "QRoundSphere"], Item["coordinateCube", 
     "VisualizeVector.nb", CopyTag -> "coordinateCube", 
     IndexTag -> "coordinateCube"], Item["coordinateCircles", 
     "VisualizeVector.nb", CopyTag -> "coordinateCircles", 
     IndexTag -> "coordinateCircles"], Item["graphicElements", 
     "VisualizeVector.nb", CopyTag -> "graphicElements", 
     IndexTag -> "graphicElements"]}], Item[Delimiter]}]
